### PR TITLE
Add .NET analyzer #44

### PR DESCRIPTION
**Pull request by roxk**
connect #44
requires #48

- [x] Fix remaining warnings
- [x] Enable warning as error
- [x] Add test for resuming on main thread in user code

### CODE REVIEW

**Review by louischan-oursky — COMMENTED** [review]
IMG_3209

Not sure if this is related to `ConfigureAsync(false)`. That change seems very dangerous to me though...

**Comment by roxk** [comment]
Oh, this reveals a bug in the lock code, lemme fix.

**Comment by louischan-oursky** [comment]
Can't we turn off the explicit `ConfigureAwait(false)` rule? For IO intensive await, we can add it to get real benefits.

**Comment by roxk** [comment]
Technically yes, but we shouldn't as that is just covering bugs. It's also no about IO intensive await (it's the reverse - for IO intensive await, the IO wait time would trump the thread switching overhead).

**Comment by louischan-oursky** [comment]
Can we ensure (in static analysis sense) when we call platform framework code, we are always on main thread? I guess that is most likely to cause bugs.

**Comment by roxk** [comment]
> Can we ensure (in static analysis sense) when we call platform framework code, we are always on main thread?

No methods that I'm aware of. Even in vanilla android it's not possible. Best we can do is test it in our test app for now (which is why I added the assertion in sample app).

One way is to defensively dispatch on main thread for all platform code but that is IMO unnecessary, and hurts perf unnecessarily.

As for the exception, seems like we are hitting a bug in mono's implementation of reader write lock slim. The symptom is similar to [this bug](https://bugzilla.xamarin.com/66/6635/bug.html) but it's said to be fixed in 2012.

For now, I think it's acceptable to only resume on original (captured) context for this method.

**Comment by louischan-oursky** [comment]
IMG_3210

I got this exception when I press Open Settings. I guess we better stick with not calling `ConfigureAsync(false)`

**Comment by roxk** [comment]
I think we should fix by properly queuing that particular call to ui thread. Lemme fix. For some reason VS for mac had issues running the test app on my mac mini so you might need to wait a bit longer.

**Pull request merged**
